package hello.model.ddb;


import javax.persistence.Entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "PhotoInfo")
public class PhotoInfo {
    private String id;
    
		private String img_id;
    private String locale;
    private String imgInfo;
    
    public PhotoInfo() {
    }
    
    public PhotoInfo(String img_id, String locale, String imgInfo) {
        this.img_id = img_id;
        this.locale = locale;
        this.imgInfo = imgInfo;
    }
 
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
 
    @DynamoDBAttribute
    public String getImg_id() {
 			return img_id;
 		}
 
    @DynamoDBAttribute
 		public String getLocale() {
 			return locale;
 		}
    
    @DynamoDBAttribute
		public String getImgInfo() {
 			return imgInfo;
 		}
    
 		public void setId(String id) {
 			this.id = id;
 		}
    
 		public void setImg_id(String img_id) {
 			this.img_id = img_id;
 		}

 		public void setLocale(String locale) {
 			this.locale = locale;
 		}

 		public void setImgInfo(String imgInfo) {
 			this.imgInfo = imgInfo;
 		}

		
	  @Override
	  public boolean equals(Object o) {
	      if (this == o) return true;
	      if (o == null || getClass() != o.getClass()) return false;

	      PhotoInfo p = (PhotoInfo) o;

	      return id.equals(p.id);
	  }

	  @Override
	  public int hashCode() {
	      return id.hashCode();
	  }
}
