package hello.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import hello.model.PhotoInfo;
import hello.repository.PhotoInfoRepository;;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/workshop/photos") // This means URL's start with /workshop (after Application path)
public class PhotoInfoController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private PhotoInfoRepository phtoInfoRepository;

	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewPhotoInfo (@RequestParam String img_id
			, @RequestParam String locale , @RequestParam String img_info) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		PhotoInfo n = new PhotoInfo();

		n.setImg_id(Integer.parseInt(img_id));
		n.setLocale(locale);
		n.setImgInfo(img_info);
		phtoInfoRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<PhotoInfo> getAllUsers() {
		// This returns a JSON or XML with the users
		return phtoInfoRepository.findAll();
	}
	
	@GetMapping(path="/deleteall")
	public @ResponseBody String deleteAllUsers() {
		// This returns a JSON or XML with the users
		try {
			phtoInfoRepository.deleteAll();
			return "OK";
		} catch (Exception e) {
			return "Deletel all Error";
		}
	
	}
}

